export interface Library {
  name: string;
  subdomain: string;
  location: string;
}

export const LIBRARIES: Library[] = [
  { name: "Alameda County Library", subdomain: "aclibrary", location: "Alameda County, CA" },
  { name: "Allegheny County Libraries", subdomain: "acl", location: "Allegheny County, PA" },
  { name: "Arapahoe Libraries", subdomain: "arapahoelibraries", location: "Arapahoe County, CO" },
  { name: "Aurora Public Library", subdomain: "aurora", location: "Aurora, ON, Canada" },
  { name: "Austin Public Library", subdomain: "austin", location: "Austin, TX" },
  { name: "Barrie Public Library", subdomain: "barrie", location: "Barrie, ON, Canada" },
  { name: "Belleville Public Library", subdomain: "belleville", location: "Belleville, ON, Canada" },
  { name: "Beverly Hills Public Library", subdomain: "beverlyhills", location: "Beverly Hills, CA" },
  { name: "Boca Raton Public Library", subdomain: "bocalibrary", location: "Boca Raton, FL" },
  { name: "Boston Public Library", subdomain: "bpl", location: "Boston, MA" },
  { name: "Brantford Public Library", subdomain: "brantford", location: "Brantford, ON, Canada" },
  { name: "Brockville Public Library", subdomain: "brockville", location: "Brockville, ON, Canada" },
  { name: "Burlington Public Library", subdomain: "burlington", location: "Burlington, ON, Canada" },
  { name: "Burnaby Public Library", subdomain: "burnaby", location: "Burnaby, BC, Canada" },
  { name: "Calgary Public Library", subdomain: "calgary", location: "Calgary, AB, Canada" },
  { name: "Caledon Public Library", subdomain: "caledon", location: "Caledon, ON, Canada" },
  { name: "Cambridge Public Library (Idea Exchange)", subdomain: "ideaexchange", location: "Cambridge, ON, Canada" },
  { name: "Canton Public Library", subdomain: "cantonpl", location: "Canton, MI" },
  { name: "Central Arkansas Library System", subdomain: "cals", location: "Little Rock, AR" },
  { name: "Chandler Public Library", subdomain: "chandler", location: "Chandler, AZ" },
  { name: "Chapel Hill Public Library", subdomain: "chpl", location: "Chapel Hill, NC" },
  { name: "Charlotte Mecklenburg Library", subdomain: "cmlibrary", location: "Charlotte, NC" },
  { name: "Chicago Public Library", subdomain: "chipublib", location: "Chicago, IL" },
  { name: "Chinook Arch Regional Library System", subdomain: "chinookarch", location: "Lethbridge, AB, Canada" },
  { name: "Christchurch City Libraries", subdomain: "christchurch", location: "Christchurch, New Zealand" },
  { name: "Cincinnati & Hamilton County Public Library", subdomain: "cincinnatilibrary", location: "Cincinnati, OH" },
  { name: "Columbus Metropolitan Library", subdomain: "cml", location: "Columbus, OH" },
  { name: "Contra Costa County Library", subdomain: "ccclib", location: "Contra Costa County, CA" },
  { name: "Daniel Boone Regional Library", subdomain: "dbrl", location: "Columbia, MO" },
  { name: "Daviess County Public Library", subdomain: "dcpl", location: "Owensboro, KY" },
  { name: "Dayton Metro Library", subdomain: "dayton", location: "Dayton, OH" },
  { name: "Denton Public Library", subdomain: "denton", location: "Denton, TX" },
  { name: "Deschutes Public Library", subdomain: "dpl", location: "Deschutes County, OR" },
  { name: "Douglas County Libraries", subdomain: "dcl", location: "Douglas County, CO" },
  { name: "Durham County Library", subdomain: "durhamcounty", location: "Durham, NC" },
  { name: "East Chicago Public Library", subdomain: "ec", location: "East Chicago, IN" },
  { name: "East Lansing Public Library", subdomain: "elpl", location: "East Lansing, MI" },
  { name: "Edmonton Public Library", subdomain: "epl", location: "Edmonton, AB, Canada" },
  { name: "Evanston Public Library", subdomain: "evanstonlibrary", location: "Evanston, IL" },
  { name: "Fraser Valley Regional Library", subdomain: "fvrl", location: "Fraser Valley, BC, Canada" },
  { name: "Fulton County Library System", subdomain: "fulcolibrary", location: "Fulton County, GA" },
  { name: "Georgina Public Library", subdomain: "georgina", location: "Georgina, ON, Canada" },
  { name: "Glenview Public Library", subdomain: "glenviewpl", location: "Glenview, IL" },
  { name: "Grand Rapids Public Library", subdomain: "grpl", location: "Grand Rapids, MI" },
  { name: "Greater Sudbury Public Library", subdomain: "gspl", location: "Sudbury, ON, Canada" },
  { name: "Greenwich Library", subdomain: "greenwichlibrary", location: "Greenwich, CT" },
  { name: "Halifax Public Libraries", subdomain: "halifax", location: "Halifax, NS, Canada" },
  { name: "Hamilton Public Library", subdomain: "hpl", location: "Hamilton, ON, Canada" },
  { name: "Harris County Public Library", subdomain: "hcpl", location: "Houston, TX" },
  { name: "Hayward Public Library", subdomain: "hayward", location: "Hayward, CA" },
  { name: "Hennepin County Library", subdomain: "hclib", location: "Minneapolis, MN" },
  { name: "Herrick District Library", subdomain: "herrickdl", location: "Holland, MI" },
  { name: "Hillsborough County Public Library Cooperative", subdomain: "hcplc", location: "Tampa, FL" },
  { name: "Indianapolis Public Library", subdomain: "indypl", location: "Indianapolis, IN" },
  { name: "Innisfil Public Library", subdomain: "innisfil", location: "Innisfil, ON, Canada" },
  { name: "Jefferson County Public Library", subdomain: "jeffcolibrary", location: "Jefferson County, CO" },
  { name: "Johnson County Library", subdomain: "jocolibrary", location: "Johnson County, KS" },
  { name: "Kansas City Public Library", subdomain: "kclibrary", location: "Kansas City, MO" },
  { name: "Kent District Library", subdomain: "kdl", location: "Grand Rapids area, MI" },
  { name: "Kenton County Public Library", subdomain: "kentonlibrary", location: "Covington, KY" },
  { name: "King County Library System", subdomain: "kcls", location: "King County, WA" },
  { name: "Kitsap Regional Library", subdomain: "krl", location: "Kitsap County, WA" },
  { name: "Lakeland Library Cooperative", subdomain: "llc", location: "Western MI" },
  { name: "Las Vegas-Clark County Library District", subdomain: "lvccld", location: "Las Vegas, NV" },
  { name: "Lawrence Public Library", subdomain: "lawrence", location: "Lawrence, KS" },
  { name: "Malden Public Library", subdomain: "mpl", location: "Malden, MA" },
  { name: "Margate City Public Library", subdomain: "margate", location: "Margate City, NJ" },
  { name: "Marin County Free Library", subdomain: "marinlibrary", location: "Marin County, CA" },
  { name: "MARINet", subdomain: "marinet", location: "Marin County, CA" },
  { name: "Markham Public Library", subdomain: "markham", location: "Markham, ON, Canada" },
  { name: "Mid-Continent Public Library", subdomain: "mymcpl", location: "Kansas City metro, MO" },
  { name: "Mississauga Library", subdomain: "mississauga", location: "Mississauga, ON, Canada" },
  { name: "Montmorency County Public Library", subdomain: "mcpl", location: "Atlanta, MI" },
  { name: "MORE Libraries (IFLS Library System)", subdomain: "more", location: "Western WI" },
  { name: "Multnomah County Library", subdomain: "multcolib", location: "Portland, OR" },
  { name: "Muskegon Area District Library", subdomain: "muskegonadl", location: "Muskegon, MI" },
  { name: "Naperville Public Library", subdomain: "naperlib", location: "Naperville, IL" },
  { name: "New Westminster Public Library", subdomain: "newwestminster", location: "New Westminster, BC, Canada" },
  { name: "Norfolk County Public Library", subdomain: "ncpl", location: "Norfolk County, ON, Canada" },
  { name: "Oakland Public Library", subdomain: "oaklandlibrary", location: "Oakland, CA" },
  { name: "Oakville Public Library", subdomain: "opl", location: "Oakville, ON, Canada" },
  { name: "Omaha Public Library", subdomain: "omaha", location: "Omaha, NE" },
  { name: "Ottawa Public Library", subdomain: "ottawa", location: "Ottawa, ON, Canada" },
  { name: "Palm Beach County Library System", subdomain: "pbclibrary", location: "Palm Beach County, FL" },
  { name: "Palo Alto City Library", subdomain: "paloalto", location: "Palo Alto, CA" },
  { name: "Pickering Public Library", subdomain: "pickering", location: "Pickering, ON, Canada" },
  { name: "Pima County Public Library", subdomain: "pima", location: "Tucson, AZ" },
  { name: "Princeton Public Library", subdomain: "princetonlibrary", location: "Princeton, NJ" },
  { name: "Redwood City Public Library", subdomain: "rcpl", location: "Redwood City, CA" },
  { name: "Richmond Public Library", subdomain: "yourlibrary", location: "Richmond, BC, Canada" },
  { name: "Saint Paul Public Library", subdomain: "sppl", location: "Saint Paul, MN" },
  { name: "San Antonio Public Library", subdomain: "mysapl", location: "San Antonio, TX" },
  { name: "San Diego Public Library", subdomain: "sandiego", location: "San Diego, CA" },
  { name: "San Francisco Public Library", subdomain: "sfpl", location: "San Francisco, CA" },
  { name: "San Jose Public Library", subdomain: "sjpl", location: "San Jose, CA" },
  { name: "San Mateo County Libraries", subdomain: "smcl", location: "San Mateo County, CA" },
  { name: "Santa Clara County Library", subdomain: "sccl", location: "Santa Clara County, CA" },
  { name: "Seattle Public Library", subdomain: "seattle", location: "Seattle, WA" },
  { name: "Sno-Isle Libraries", subdomain: "sno-isle", location: "Snohomish & Island Counties, WA" },
  { name: "Sonoma County Library", subdomain: "sonoma", location: "Sonoma County, CA" },
  { name: "South San Francisco Public Library", subdomain: "ssf", location: "South San Francisco, CA" },
  { name: "St. Louis Public Library", subdomain: "slpl", location: "St. Louis, MO" },
  { name: "St. Thomas Public Library", subdomain: "stthomas", location: "St. Thomas, ON, Canada" },
  { name: "Stratford Public Library", subdomain: "spl", location: "Stratford, ON, Canada" },
  { name: "Strathcona County Library", subdomain: "scl", location: "Strathcona County, AB, Canada" },
  { name: "Surrey Libraries", subdomain: "surrey", location: "Surrey, BC, Canada" },
  { name: "Tacoma Public Library", subdomain: "tacoma", location: "Tacoma, WA" },
  { name: "Toledo Library", subdomain: "toledo", location: "Toledo, OH" },
  { name: "Toronto Public Library", subdomain: "tpl", location: "Toronto, ON, Canada" },
  { name: "Tulsa City-County Library", subdomain: "tccl", location: "Tulsa, OK" },
  { name: "Vancouver Public Library", subdomain: "vpl", location: "Vancouver, BC, Canada" },
  { name: "Warren County Public Library", subdomain: "wcpl", location: "Bowling Green, KY" },
  { name: "Washington County Cooperative Library Services", subdomain: "wccls", location: "Washington County, OR" },
  { name: "Wellington County Library", subdomain: "wellington", location: "Wellington County, ON, Canada" },
  { name: "West Perth Public Library", subdomain: "wppl", location: "West Perth, ON, Canada" },
  { name: "Woodstock Public Library", subdomain: "woodstock", location: "Woodstock, ON, Canada" },
];

export function searchLibraries(query: string): Library[] {
  const q = query.toLowerCase();
  return LIBRARIES.filter(
    (lib) =>
      lib.name.toLowerCase().includes(q) ||
      lib.location.toLowerCase().includes(q) ||
      lib.subdomain.toLowerCase().includes(q)
  ).slice(0, 10);
}

export function findLibrary(subdomain: string): Library | undefined {
  return LIBRARIES.find((lib) => lib.subdomain === subdomain);
}
